# constants.py
import random

WIDTH, HEIGHT = 800, 600
FPS = 60

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

DAILY_DEATH_CHANCE = 0.15
POSITIVE_EVENT_CHANCE = 0.60
RANDOM_RANGE_EVENT = 100
STARTING_SPINS = 8

EXPEDITION_FOOD_LOSS_MULT = 1.0
EXPEDITION_HP_LOSS_MULT = 1.0
EXTRA_EXPEDITION_SPIN_MIN = 5
EXTRA_EXPEDITION_SPIN_MAX = 7

FOOD_DRAIN_HIGH = 10
FOOD_DRAIN_LOW = 20
HEALTH_DAMAGE_NO_FOOD = 20
EXPEDITION_COOLDOWN = 5

MATH_TIME_LIMIT = 6  # default

def get_random_int():
    return random.randint(0, RANDOM_RANGE_EVENT)
